# This file create a environment with kubeipam syncing with netbox and provide
# ip address for multus cni.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeipam
rules:
  - apiGroups: ["ipam.k8s.cc.cs.nctu.edu.tw"]
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeipam
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeipam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeipam
subjects:
- kind: ServiceAccount
  name: kubeipam
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubeipam-cni-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: kubeipam-cni
    name: kubeipam-cni
spec:
  selector:
    matchLabels:
      name: kubeipam-cni
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: kubeipam-cni
        name: kubeipam-cni
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: kubeipam
      containers:
        - name: kubeipam-cni
          image: jbliao/kubeipam-cni
          command: ["/entrypoint.sh"]
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
            - name: cniconf
              mountPath: /host/etc/cni/net.d
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: cniconf
          hostPath:
            path: /etc/cni/net.d/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeipam-controller
  namespace: kube-system
  labels:
    app: kubeipam-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeipam-controller
  template:
    metadata:
      labels:
        app: kubeipam-controller
    spec:
      serviceAccountName: kubeipam
      containers:
        - name: kubeipam-controller
          image: jbliao/controller
---
apiVersion: ipam.k8s.cc.cs.nctu.edu.tw/v1alpha1
kind: IPPool
metadata:
  name: ippool-sample
spec:
  type: "netbox"
  addresses: []
  allocations: []
  rawConfig: |
    {
      "host": "10.99.198.98",
      "apiKey": "0123456789abcdef0123456789abcdef01234567",
      "prefix": "10.20.20.0/24"
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
spec:
  config: |
    {
      "cniVersion": "0.3.0",
        "type": "bridge",
        "name": "multus",
        "master": "multus0",
        "ipam": {
          "type": "kubeipam-cni",
          "configPath": "/etc/cni/net.d/kubeipam.kubeconfig",
          "poolName": "ippool-sample",
          "poolNamespace": "default",
          "mask": "255.255.255.0",
          "gateway": "10.20.20.254",
          "routes": ["10.20.0.0/16"],
          "logFile": "/var/log/kubeipam.log"
        }
    }