
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ipam.k8s.cc.cs.nctu.edu.tw
  resources:
  - ippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.k8s.cc.cs.nctu.edu.tw
  resources:
  - ippools/status
  verbs:
  - get
  - patch
  - update
