apiVersion: ipam.k8s.cc.cs.nctu.edu.tw/v1alpha1
kind: IPPool
metadata:
  name: ippool-sample
spec:
  type: "netbox"
  addresses: []
  allocations: []
  rawConfig: |
    {
      "host": "10.99.198.98",
      "apiKey": "0123456789abcdef0123456789abcdef01234567",
      "prefix": "10.20.20.0/24"
    }
